version: '3.8'

services:
  api:
    container_name: ${CONTAINER_SERVER}_${NODE_ENV}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:3000
    volumes:
      - ./files:/usr/src/app/files
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
      PORT: ${PORT}
      SERVER_URL: ${SERVER_URL}
      DB_DIALECT: ${DB_DIALECT}
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: ${CONTAINER_POSTGRES}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: ${CONTAINER_ADMINER}
    restart: always
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - postgres

volumes:
  postgres_data: