export const SEQUELIZE = 'SEQUELIZE';

// List of Repositories
export const GRANTS_REPOSITORY = 'GRANTS_REPOSITORY';
export const GRANTS_HISTORY_REPOSITORY = 'GRANTS_HISTORY_REPOSITORY';
export const STATUSES_REPOSITORY = 'STATUSES_REPOSITORY';
export const USERS_REPOSITORY = 'USERS_REPOSITORY';
